-- Create Database Trigger --
SET DEFINE OFF;
CREATE OR REPLACE TRIGGER CAPTAR.CABLE_INSTALL_UPLOAD_EXT_AIUDR
    AFTER INSERT OR UPDATE OR DELETE ON CABLE_INSTALL_UPLOAD_EXTRA
    FOR EACH ROW
DECLARE
    JN_OPERATION VARCHAR2(3);
BEGIN
    IF INSERTING THEN
        JN_OPERATION := 'INS';
    ELSIF UPDATING THEN
        JN_OPERATION := 'UPD';
    ELSIF DELETING THEN
        JN_OPERATION := 'DEL';
    END IF;
    IF INSERTING OR UPDATING THEN
        INSERT INTO CABLE_INSTALL_UPLOAD_EXTRA_JN 
        ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , CABLENUM, SECTOR_AREA_SOURCE, BEAMLINE_AREA
         , SECTOR_GROUP, PENETRATION, PENETRATION_II, PROJECT
         , INSTALLED_LENGTH, AREA_CODE, PHASE, SECTOR_AREA_DEST
	 , CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL, userenv('sessionid')
         , :NEW.CABLENUM, :NEW.SECTOR_AREA_SOURCE, :NEW.BEAMLINE_AREA
         , :NEW.SECTOR_GROUP, :NEW.PENETRATION, :NEW.PENETRATION_II, :NEW.PROJECT
         , :NEW.INSTALLED_LENGTH, :NEW.AREA_CODE, :NEW.PHASE, :NEW.SECTOR_AREA_DEST
	 , :NEW.CREATED_BY, :NEW.CREATED_DATE, :NEW.MODIFIED_BY, :NEW.MODIFIED_DATE
         );
     END IF;
     IF DELETING THEN
         INSERT INTO CABLE_INSTALL_UPLOAD_EXTRA_JN 
         ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , CABLENUM, SECTOR_AREA_SOURCE, BEAMLINE_AREA
         , SECTOR_GROUP, PENETRATION, PENETRATION_II, PROJECT
         , INSTALLED_LENGTH, AREA_CODE, PHASE, SECTOR_AREA_DEST
	 , CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL,userenv('sessionid')
         , :OLD.CABLENUM, :OLD.SECTOR_AREA_SOURCE, :OLD.BEAMLINE_AREA
         , :OLD.SECTOR_GROUP, :OLD.PENETRATION, :OLD.PENETRATION_II, :OLD.PROJECT
         , :OLD.INSTALLED_LENGTH, :OLD.AREA_CODE, :OLD.PHASE, :OLD.SECTOR_AREA_DEST
	 , :OLD.CREATED_BY, :OLD.CREATED_DATE, :OLD.MODIFIED_BY, :OLD.MODIFIED_DATE );
         END IF; 
END;
/

