alter table magnet_string add (
SAFETY_SYSTEM	NUMBER(2),
SAFETY_BCS	NUMBER(1),
SAFETY_PPS	NUMBER(1),
SAFETY_MPS	NUMBER(1),
STDZ_FUNC	VARCHAR2(20),
DEGAUSS_FUNC	VARCHAR2(20),
CALIB_FUNC	VARCHAR2(20),
DEGAUSS_SETL	NUMBER,
DEGAUSS_RAMP_RATE	NUMBER,
DEGAUSS_WF_UOM	VARCHAR2(20),
DEGAUSS_RAMP_RATE_UOM	VARCHAR2(20),
DEGAUSS_SETL_UOM	VARCHAR2(20),
DEGAUSS_STEP_SIZE	NUMBER,
DEGAUSS_STEP_SIZE_UOM	VARCHAR2(20),
DEGAUSS_WF_ELEM_CNT	NUMBER(4),
DEGAUSS_WF	VARCHAR2(4000)
);

alter table magnet_string_jn add (
SAFETY_SYSTEM	NUMBER(2),
SAFETY_BCS	NUMBER(1),
SAFETY_PPS	NUMBER(1),
SAFETY_MPS	NUMBER(1),
STDZ_FUNC	VARCHAR2(20),
DEGAUSS_FUNC	VARCHAR2(20),
CALIB_FUNC	VARCHAR2(20),
DEGAUSS_SETL	NUMBER,
DEGAUSS_RAMP_RATE	NUMBER,
DEGAUSS_WF_UOM	VARCHAR2(20),
DEGAUSS_RAMP_RATE_UOM	VARCHAR2(20),
DEGAUSS_SETL_UOM	VARCHAR2(20),
DEGAUSS_STEP_SIZE	NUMBER,
DEGAUSS_STEP_SIZE_UOM	VARCHAR2(20),
DEGAUSS_WF_ELEM_CNT	NUMBER(4),
DEGAUSS_WF	VARCHAR2(4000)
);
/*
alter table magnet_string modify (
SAFETY_SYSTEM	NUMBER(2));
alter table magnet_string_jn modify (
SAFETY_SYSTEM	NUMBER(2));
*/