--Add column to CONNINV
ALTER TABLE CAPTAR.CONNINV ADD (
ORIGIN             VARCHAR2(1));

--Add column to CONNINV_JN
ALTER TABLE CAPTAR.CONNINV_JN ADD (
OLD_ORIGIN             VARCHAR2(1),
NEW_ORIGIN             VARCHAR2(1));