
  CREATE OR REPLACE VIEW "CAPTAR"."V_CONNINV_HISTORY" ("EVENT", "EVENT_DATE", "CONNINV_ID", "CREATED_BY", "CREATED_DATE", "MODIFIED_BY", "MODIFIED_DATE", "ORIGIN_DEST", "LOC", "RACK", "SIDE", "ELE", "SLOT", "CONNNUM", "PINLIST", "CABLENUM", "CONNTYPE", "STATION", "INSTR", "STATION_OLD") AS 
  select EVENT,
EVENT_DATE,
CONNINV_ID,
CREATED_BY,
CREATED_DATE,
MODIFIED_BY,
MODIFIED_DATE,
ORIGIN_DEST,
LOC,
RACK,
SIDE,
ELE,
SLOT,
CONNNUM,
PINLIST,
CABLENUM,
CONNTYPE,
STATION,
INSTR,
STATION_OLD
FROM
(
SELECT
-------------
 (CASE T.JN_OPERATION
             WHEN 'INS' THEN 'Created'
             WHEN 'UPD' THEN 'Modified'
             WHEN 'DEL' THEN 'Deleted'
 END
 ) AS EVENT,
 ------------------
T.EVENT_DATE,
T.CONNINV_ID,
T.CREATED_BY,
T.CREATED_DATE,
T.MODIFIED_BY,
T.MODIFIED_DATE,
T.ORIGIN_DEST,
T.LOC,
T.RACK,
T.SIDE,
T.ELE,
T.SLOT,
T.CONNNUM,
T.PINLIST,
T.CABLENUM,
T.CONNTYPE,
T.STATION,
T.INSTR,
T.STATION_OLD
FROM
(
SELECT
       X.JN_OPERATION,
       X.JN_DATETIME AS EVENT_DATE,
       X.CONNINV_ID,
       X.CREATED_BY,
	X.CREATED_DATE,
	X.MODIFIED_BY,
	X.MODIFIED_DATE,
(CASE X.JN_OPERATION WHEN 'INS' THEN NEW_ORIGIN  WHEN 'UPD' THEN  CASE WHEN (X.OLD_ORIGIN = X.NEW_ORIGIN) THEN X.OLD_ORIGIN  ELSE '<font color=red>'||X.OLD_ORIGIN||' -> '||X.NEW_ORIGIN ||'</font>'   END   WHEN 'DEL' THEN X.OLD_ORIGIN END ) AS ORIGIN_DEST,
(CASE X.JN_OPERATION WHEN 'INS' THEN NEW_LOC  WHEN 'UPD' THEN  CASE WHEN (X.OLD_LOC = X.NEW_LOC) THEN X.OLD_LOC  ELSE '<font color=red>'||X.OLD_LOC||' -> '||X.NEW_LOC ||'</font>'   END   WHEN 'DEL' THEN X.OLD_LOC END ) AS LOC,
(CASE X.JN_OPERATION WHEN 'INS' THEN NEW_RACK  WHEN 'UPD' THEN  CASE WHEN (X.OLD_RACK = X.NEW_RACK) THEN X.OLD_RACK  ELSE '<font color=red>'||X.OLD_RACK||' -> '||X.NEW_RACK ||'</font>'   END   WHEN 'DEL' THEN X.OLD_RACK END ) AS RACK,
(CASE X.JN_OPERATION WHEN 'INS' THEN NEW_SIDE  WHEN 'UPD' THEN  CASE WHEN (X.OLD_SIDE = X.NEW_SIDE) THEN X.OLD_SIDE  ELSE '<font color=red>'||X.OLD_SIDE||' -> '||X.NEW_SIDE ||'</font>'   END   WHEN 'DEL' THEN X.OLD_SIDE END ) AS SIDE,
(CASE X.JN_OPERATION WHEN 'INS' THEN NEW_ELE  WHEN 'UPD' THEN  CASE WHEN (X.OLD_ELE = X.NEW_ELE) THEN X.OLD_ELE  ELSE '<font color=red>'||X.OLD_ELE||' -> '||X.NEW_ELE ||'</font>'   END   WHEN 'DEL' THEN X.OLD_ELE END ) AS ELE,
(CASE X.JN_OPERATION WHEN 'INS' THEN NEW_SLOT  WHEN 'UPD' THEN  CASE WHEN (X.OLD_SLOT = X.NEW_SLOT) THEN X.OLD_SLOT  ELSE '<font color=red>'||X.OLD_SLOT||' -> '||X.NEW_SLOT ||'</font>'   END   WHEN 'DEL' THEN X.OLD_SLOT END ) AS SLOT,
(CASE X.JN_OPERATION WHEN 'INS' THEN NEW_CONNNUM  WHEN 'UPD' THEN  CASE WHEN (X.OLD_CONNNUM = X.NEW_CONNNUM) THEN X.OLD_CONNNUM  ELSE '<font color=red>'||X.OLD_CONNNUM||' -> '||X.NEW_CONNNUM ||'</font>'   END   WHEN 'DEL' THEN X.OLD_CONNNUM END ) AS CONNNUM,
(CASE X.JN_OPERATION WHEN 'INS' THEN NEW_PINLIST  WHEN 'UPD' THEN  CASE WHEN (X.OLD_PINLIST = X.NEW_PINLIST) THEN X.OLD_PINLIST  ELSE '<font color=red>'||X.OLD_PINLIST||' -> '||X.NEW_PINLIST ||'</font>'   END   WHEN 'DEL' THEN X.OLD_PINLIST END ) AS PINLIST,
(CASE X.JN_OPERATION WHEN 'INS' THEN NEW_CABLENUM  WHEN 'UPD' THEN  CASE WHEN (X.OLD_CABLENUM = X.NEW_CABLENUM) THEN X.OLD_CABLENUM  ELSE '<font color=red>'||X.OLD_CABLENUM||' -> '||X.NEW_CABLENUM ||'</font>'   END   WHEN 'DEL' THEN X.OLD_CABLENUM END ) AS CABLENUM,
(CASE X.JN_OPERATION WHEN 'INS' THEN NEW_CONNTYPE  WHEN 'UPD' THEN  CASE WHEN (X.OLD_CONNTYPE = X.NEW_CONNTYPE) THEN X.OLD_CONNTYPE  ELSE '<font color=red>'||X.OLD_CONNTYPE||' -> '||X.NEW_CONNTYPE ||'</font>'   END   WHEN 'DEL' THEN X.OLD_CONNTYPE END ) AS CONNTYPE,
(CASE X.JN_OPERATION WHEN 'INS' THEN NEW_STATION  WHEN 'UPD' THEN  CASE WHEN (X.OLD_STATION = X.NEW_STATION) THEN X.OLD_STATION  ELSE '<font color=red>'||X.OLD_STATION||' -> '||X.NEW_STATION ||'</font>'   END   WHEN 'DEL' THEN X.OLD_STATION END ) AS STATION,
(CASE X.JN_OPERATION WHEN 'INS' THEN NEW_INSTR  WHEN 'UPD' THEN  CASE WHEN (X.OLD_INSTR = X.NEW_INSTR) THEN X.OLD_INSTR  ELSE '<font color=red>'||X.OLD_INSTR||' -> '||X.NEW_INSTR ||'</font>'   END   WHEN 'DEL' THEN X.OLD_INSTR END ) AS INSTR,
(CASE X.JN_OPERATION WHEN 'INS' THEN NEW_STATION_OLD  WHEN 'UPD' THEN  CASE WHEN (X.OLD_STATION_OLD = X.NEW_STATION_OLD) THEN X.OLD_STATION_OLD  ELSE '<font color=red>'||X.OLD_STATION_OLD||' -> '||X.NEW_STATION_OLD ||'</font>'   END   WHEN 'DEL' THEN X.OLD_STATION_OLD END ) AS STATION_OLD
FROM
(
SELECT
LJ.JN_OPERATION,
LJ.JN_DATETIME,
LJ.CONNINV_ID,
LJ.CREATED_BY,
LJ.CREATED_DATE,
LJ.MODIFIED_BY,
LJ.MODIFIED_DATE,
NVL(decode(LJ.OLD_ORIGIN,'Y','ORIGIN','N','DESTINATION'),'Null') AS OLD_ORIGIN,
NVL(decode(LJ.NEW_ORIGIN,'Y','ORIGIN','N','DESTINATION'),'Null') AS NEW_ORIGIN,
NVL(LJ.OLD_LOC,'Null') AS OLD_LOC,
NVL(LJ.NEW_LOC,'Null') AS NEW_LOC,
NVL(LJ.OLD_RACK,'Null') AS OLD_RACK,
NVL(LJ.NEW_RACK,'Null') AS NEW_RACK,
NVL(LJ.OLD_SIDE,'Null') AS OLD_SIDE,
NVL(LJ.NEW_SIDE,'Null') AS NEW_SIDE,
NVL(TO_CHAR(LJ.OLD_ELE),'Null') AS OLD_ELE,
NVL(TO_CHAR(LJ.NEW_ELE),'Null') AS NEW_ELE,
NVL(LJ.OLD_SLOT,'Null') AS OLD_SLOT,
NVL(LJ.NEW_SLOT,'Null') AS NEW_SLOT,
NVL(LJ.OLD_CONNNUM,'Null') AS OLD_CONNNUM,
NVL(LJ.NEW_CONNNUM,'Null') AS NEW_CONNNUM,
NVL(LJ.OLD_PINLIST,'Null') AS OLD_PINLIST,
NVL(LJ.NEW_PINLIST,'Null') AS NEW_PINLIST,
NVL(LJ.OLD_CABLENUM,'Null') AS OLD_CABLENUM,
NVL(LJ.NEW_CABLENUM,'Null') AS NEW_CABLENUM,
NVL(LJ.OLD_CONNTYPE,'Null') AS OLD_CONNTYPE,
NVL(LJ.NEW_CONNTYPE,'Null') AS NEW_CONNTYPE,
NVL(TO_CHAR(LJ.OLD_STATION),'Null') AS OLD_STATION,
NVL(TO_CHAR(LJ.NEW_STATION),'Null') AS NEW_STATION,
NVL(LJ.OLD_INSTR,'Null') AS OLD_INSTR,
NVL(LJ.NEW_INSTR,'Null') AS NEW_INSTR,
NVL(LJ.OLD_STATION_OLD,'Null') AS OLD_STATION_OLD,
NVL(LJ.NEW_STATION_OLD,'Null') AS NEW_STATION_OLD
FROM
CONNINV_JN LJ
) X
) T
) Z
;
