alter table ssrl_rsw_form add (
S6_OPERATOR_ACK			VARCHAR2(1),
--S6_OPERATOR_ACK_ID		NUMBER,
S6_OPERATOR_ACK_DATE		DATE,
S6_OPERATOR_ACK_MODIFIED_BY	VARCHAR2(30)
);

alter table ssrl_rsw_form_jn add (
S6_OPERATOR_ACK			VARCHAR2(1),
--S6_OPERATOR_ACK_ID		NUMBER,
S6_OPERATOR_ACK_DATE		DATE,
S6_OPERATOR_ACK_MODIFIED_BY	VARCHAR2(30)
);