create or replace TRIGGER SSRL_RSW_FORM_AIUDR
  AFTER INSERT OR DELETE OR UPDATE ON SSRL_RSW_FORM
  REFERENCING FOR EACH ROW
  DECLARE
    JN_OPERATION VARCHAR2(3);
BEGIN
    IF INSERTING THEN
        JN_OPERATION := 'INS';
    ELSIF UPDATING THEN
        JN_OPERATION := 'UPD';
    ELSIF DELETING THEN
        JN_OPERATION := 'DEL';
    END IF;
    IF INSERTING OR UPDATING THEN
        INSERT INTO SSRL_RSW_FORM_JN 
        ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , SSRL_FORM_ID, S1_PRELIM_1, S1_PRELIM_2
         , FORM_STATUS_ID, EMAIL_CHK, EMAIL_RULE, SSRL_FORM_ID_TRANSFER_FROM
         , SSRL_FORM_ID_TRANSFER_TO, S1_TASK_PERSON_ID, S1_AREA_ID, S1_START_TIME
         , S1_DESCR, S2_DESCR_BEFORE, S2_DESCR_AFTER, S3_RAD_ID
         , S3_RAD_DATE, S3_RAD_MODIFIED_BY, S3_SSO_ID, S3_SSO_DATE
         , S3_SSO_MODIFIED_BY, S3_AREA_MGR_ID, S3_AREA_MGR_DATE, S3_AREA_MGR_MODIFIED_BY
         , S3_TASK_PERSON_ACK_ID, S3_TASK_PERSON_ACK_DATE, S3_TASK_PERSON_ACK_MODIFIED_BY, S4_OPERATOR_ID
         , S4_OPERATOR_DATE, S4_OPERATOR_MODIFIED_BY, S4_WRKR_ID, S4_WRKR_DATE
         , S4_WRKR_MODIFIED_BY, S5_TASK_PERSON_CHK, S5_TASK_PERSON_COMMENTS, S5_TASK_PERSON_ACK_ID
         , S5_TASK_PERSON_ACK_DATE, S5_TASK_PERSON_ACK_MODIFIED_BY, S5_PPS_CHK, S5_PPS_COMMENTS
         , S5_PPS_ID, S5_PPS_DATE, S5_PPS_MODIFIED_BY, S5_RAD_CHK
         , S5_RAD_COMMENTS, S5_RAD_ID, S5_RAD_DATE, S5_RAD_MODIFIED_BY
         , S5_OPERATOR_CHK, S5_OPERATOR_COMMENTS, S5_OPERATOR_ID, S5_OPERATOR_DATE
         , S5_OPERATOR_MODIFIED_BY, S5_RPFO_CHK, S5_RPFO_COMMENTS, S5_RPFO_ID
         , S5_RPFO_DATE, S5_RPFO_MODIFIED_BY
         , S5_OTHER1_CHK, S5_OTHER1_ID, S5_OTHER1_COMMENTS, S5_OTHER1_ACK_ID
         , S5_OTHER1_ACK_DATE, S5_OTHER1_ACK_MODIFIED_BY, S5_OTHER2_CHK, S5_OTHER2_ID
         , S5_OTHER2_COMMENTS, S5_OTHER2_ACK_ID, S5_OTHER2_ACK_DATE, S5_OTHER2_ACK_MODIFIED_BY
         , S5_OTHER3_CHK, S5_OTHER3_ID, S5_OTHER3_COMMENTS, S5_OTHER3_ACK_ID
         , S5_OTHER3_ACK_DATE, S5_OTHER3_ACK_MODIFIED_BY, S6_SSO_ID, S6_SSO_DATE
         , S6_SSO_MODIFIED_BY, S6_OPERATOR_ID, S6_OPERATOR_DATE, S6_OPERATOR_MODIFIED_BY
         , FOLLOWUP_COMMENTS, POST_CLOSURE_COMMENTS, CREATED_BY, CREATED_DATE
         , MODIFIED_BY, MODIFIED_DATE
	 , S4_ASSIGN_WRKR_ID, S4_ASSIGN_WRKR_DATE, S4_ASSIGN_WRKR_MODIFIED_BY, DROP_FORM_CHK
	 , S5_SSO_CHK, S5_SSO_COMMENTS, S5_SSO_ID, S5_SSO_DATE, S5_SSO_MODIFIED_BY
	 , S6_OPERATOR_ACK, S6_OPERATOR_ACK_DATE, S6_OPERATOR_ACK_MODIFIED_BY
	) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL, userenv('sessionid')
         , :NEW.SSRL_FORM_ID, :NEW.S1_PRELIM_1, :NEW.S1_PRELIM_2
         , :NEW.FORM_STATUS_ID, :NEW.EMAIL_CHK, :NEW.EMAIL_RULE, :NEW.SSRL_FORM_ID_TRANSFER_FROM
         , :NEW.SSRL_FORM_ID_TRANSFER_TO, :NEW.S1_TASK_PERSON_ID, :NEW.S1_AREA_ID, :NEW.S1_START_TIME
         , :NEW.S1_DESCR, :NEW.S2_DESCR_BEFORE, :NEW.S2_DESCR_AFTER, :NEW.S3_RAD_ID
         , :NEW.S3_RAD_DATE, :NEW.S3_RAD_MODIFIED_BY, :NEW.S3_SSO_ID, :NEW.S3_SSO_DATE
         , :NEW.S3_SSO_MODIFIED_BY, :NEW.S3_AREA_MGR_ID, :NEW.S3_AREA_MGR_DATE, :NEW.S3_AREA_MGR_MODIFIED_BY
         , :NEW.S3_TASK_PERSON_ACK_ID, :NEW.S3_TASK_PERSON_ACK_DATE, :NEW.S3_TASK_PERSON_ACK_MODIFIED_BY, :NEW.S4_OPERATOR_ID
         , :NEW.S4_OPERATOR_DATE, :NEW.S4_OPERATOR_MODIFIED_BY, :NEW.S4_WRKR_ID, :NEW.S4_WRKR_DATE
         , :NEW.S4_WRKR_MODIFIED_BY, :NEW.S5_TASK_PERSON_CHK, :NEW.S5_TASK_PERSON_COMMENTS, :NEW.S5_TASK_PERSON_ACK_ID
         , :NEW.S5_TASK_PERSON_ACK_DATE, :NEW.S5_TASK_PERSON_ACK_MODIFIED_BY, :NEW.S5_PPS_CHK, :NEW.S5_PPS_COMMENTS
         , :NEW.S5_PPS_ID, :NEW.S5_PPS_DATE, :NEW.S5_PPS_MODIFIED_BY, :NEW.S5_RAD_CHK
         , :NEW.S5_RAD_COMMENTS, :NEW.S5_RAD_ID, :NEW.S5_RAD_DATE, :NEW.S5_RAD_MODIFIED_BY
         , :NEW.S5_OPERATOR_CHK, :NEW.S5_OPERATOR_COMMENTS, :NEW.S5_OPERATOR_ID, :NEW.S5_OPERATOR_DATE
         , :NEW.S5_OPERATOR_MODIFIED_BY, :NEW.S5_RPFO_CHK, :NEW.S5_RPFO_COMMENTS, :NEW.S5_RPFO_ID
         , :NEW.S5_RPFO_DATE, :NEW.S5_RPFO_MODIFIED_BY
         , :NEW.S5_OTHER1_CHK, :NEW.S5_OTHER1_ID, :NEW.S5_OTHER1_COMMENTS, :NEW.S5_OTHER1_ACK_ID
         , :NEW.S5_OTHER1_ACK_DATE, :NEW.S5_OTHER1_ACK_MODIFIED_BY, :NEW.S5_OTHER2_CHK, :NEW.S5_OTHER2_ID
         , :NEW.S5_OTHER2_COMMENTS, :NEW.S5_OTHER2_ACK_ID, :NEW.S5_OTHER2_ACK_DATE, :NEW.S5_OTHER2_ACK_MODIFIED_BY
         , :NEW.S5_OTHER3_CHK, :NEW.S5_OTHER3_ID, :NEW.S5_OTHER3_COMMENTS, :NEW.S5_OTHER3_ACK_ID
         , :NEW.S5_OTHER3_ACK_DATE, :NEW.S5_OTHER3_ACK_MODIFIED_BY, :NEW.S6_SSO_ID, :NEW.S6_SSO_DATE
         , :NEW.S6_SSO_MODIFIED_BY, :NEW.S6_OPERATOR_ID, :NEW.S6_OPERATOR_DATE, :NEW.S6_OPERATOR_MODIFIED_BY
         , :NEW.FOLLOWUP_COMMENTS, :NEW.POST_CLOSURE_COMMENTS, :NEW.CREATED_BY, :NEW.CREATED_DATE
         , :NEW.MODIFIED_BY, :NEW.MODIFIED_DATE
	 , :NEW.S4_ASSIGN_WRKR_ID, :NEW.S4_ASSIGN_WRKR_DATE, :NEW.S4_ASSIGN_WRKR_MODIFIED_BY, :NEW.DROP_FORM_CHK
	 , :NEW.S5_SSO_CHK, :NEW.S5_SSO_COMMENTS, :NEW.S5_SSO_ID, :NEW.S5_SSO_DATE, :NEW.S5_SSO_MODIFIED_BY
	 , :NEW.S6_OPERATOR_ACK, :NEW.S6_OPERATOR_ACK_DATE, :NEW.S6_OPERATOR_ACK_MODIFIED_BY
         );
     END IF;
     IF DELETING THEN
         INSERT INTO SSRL_RSW_FORM_JN 
         ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , SSRL_FORM_ID, S1_PRELIM_1, S1_PRELIM_2
         , FORM_STATUS_ID, EMAIL_CHK, EMAIL_RULE, SSRL_FORM_ID_TRANSFER_FROM
         , SSRL_FORM_ID_TRANSFER_TO, S1_TASK_PERSON_ID, S1_AREA_ID, S1_START_TIME
         , S1_DESCR, S2_DESCR_BEFORE, S2_DESCR_AFTER, S3_RAD_ID
         , S3_RAD_DATE, S3_RAD_MODIFIED_BY, S3_SSO_ID, S3_SSO_DATE
         , S3_SSO_MODIFIED_BY, S3_AREA_MGR_ID, S3_AREA_MGR_DATE, S3_AREA_MGR_MODIFIED_BY
         , S3_TASK_PERSON_ACK_ID, S3_TASK_PERSON_ACK_DATE, S3_TASK_PERSON_ACK_MODIFIED_BY, S4_OPERATOR_ID
         , S4_OPERATOR_DATE, S4_OPERATOR_MODIFIED_BY, S4_WRKR_ID, S4_WRKR_DATE
         , S4_WRKR_MODIFIED_BY, S5_TASK_PERSON_CHK, S5_TASK_PERSON_COMMENTS, S5_TASK_PERSON_ACK_ID
         , S5_TASK_PERSON_ACK_DATE, S5_TASK_PERSON_ACK_MODIFIED_BY, S5_PPS_CHK, S5_PPS_COMMENTS
         , S5_PPS_ID, S5_PPS_DATE, S5_PPS_MODIFIED_BY, S5_RAD_CHK
         , S5_RAD_COMMENTS, S5_RAD_ID, S5_RAD_DATE, S5_RAD_MODIFIED_BY
         , S5_OPERATOR_CHK, S5_OPERATOR_COMMENTS, S5_OPERATOR_ID, S5_OPERATOR_DATE
         , S5_OPERATOR_MODIFIED_BY, S5_RPFO_CHK, S5_RPFO_COMMENTS, S5_RPFO_ID
         , S5_RPFO_DATE, S5_RPFO_MODIFIED_BY
         , S5_OTHER1_CHK, S5_OTHER1_ID, S5_OTHER1_COMMENTS, S5_OTHER1_ACK_ID
         , S5_OTHER1_ACK_DATE, S5_OTHER1_ACK_MODIFIED_BY, S5_OTHER2_CHK, S5_OTHER2_ID
         , S5_OTHER2_COMMENTS, S5_OTHER2_ACK_ID, S5_OTHER2_ACK_DATE, S5_OTHER2_ACK_MODIFIED_BY
         , S5_OTHER3_CHK, S5_OTHER3_ID, S5_OTHER3_COMMENTS, S5_OTHER3_ACK_ID
         , S5_OTHER3_ACK_DATE, S5_OTHER3_ACK_MODIFIED_BY, S6_SSO_ID, S6_SSO_DATE
         , S6_SSO_MODIFIED_BY, S6_OPERATOR_ID, S6_OPERATOR_DATE, S6_OPERATOR_MODIFIED_BY
         , FOLLOWUP_COMMENTS, POST_CLOSURE_COMMENTS, CREATED_BY, CREATED_DATE
         , MODIFIED_BY, MODIFIED_DATE
	 , S4_ASSIGN_WRKR_ID, S4_ASSIGN_WRKR_DATE, S4_ASSIGN_WRKR_MODIFIED_BY, DROP_FORM_CHK
	 , S5_SSO_CHK, S5_SSO_COMMENTS, S5_SSO_ID, S5_SSO_DATE, S5_SSO_MODIFIED_BY
	 , S6_OPERATOR_ACK, S6_OPERATOR_ACK_DATE, S6_OPERATOR_ACK_MODIFIED_BY
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL,userenv('sessionid')
         , :OLD.SSRL_FORM_ID, :OLD.S1_PRELIM_1, :OLD.S1_PRELIM_2
         , :OLD.FORM_STATUS_ID, :OLD.EMAIL_CHK, :OLD.EMAIL_RULE, :OLD.SSRL_FORM_ID_TRANSFER_FROM
         , :OLD.SSRL_FORM_ID_TRANSFER_TO, :OLD.S1_TASK_PERSON_ID, :OLD.S1_AREA_ID, :OLD.S1_START_TIME
         , :OLD.S1_DESCR, :OLD.S2_DESCR_BEFORE, :OLD.S2_DESCR_AFTER, :OLD.S3_RAD_ID
         , :OLD.S3_RAD_DATE, :OLD.S3_RAD_MODIFIED_BY, :OLD.S3_SSO_ID, :OLD.S3_SSO_DATE
         , :OLD.S3_SSO_MODIFIED_BY, :OLD.S3_AREA_MGR_ID, :OLD.S3_AREA_MGR_DATE, :OLD.S3_AREA_MGR_MODIFIED_BY
         , :OLD.S3_TASK_PERSON_ACK_ID, :OLD.S3_TASK_PERSON_ACK_DATE, :OLD.S3_TASK_PERSON_ACK_MODIFIED_BY, :OLD.S4_OPERATOR_ID
         , :OLD.S4_OPERATOR_DATE, :OLD.S4_OPERATOR_MODIFIED_BY, :OLD.S4_WRKR_ID, :OLD.S4_WRKR_DATE
         , :OLD.S4_WRKR_MODIFIED_BY, :OLD.S5_TASK_PERSON_CHK, :OLD.S5_TASK_PERSON_COMMENTS, :OLD.S5_TASK_PERSON_ACK_ID
         , :OLD.S5_TASK_PERSON_ACK_DATE, :OLD.S5_TASK_PERSON_ACK_MODIFIED_BY, :OLD.S5_PPS_CHK, :OLD.S5_PPS_COMMENTS
         , :OLD.S5_PPS_ID, :OLD.S5_PPS_DATE, :OLD.S5_PPS_MODIFIED_BY, :OLD.S5_RAD_CHK
         , :OLD.S5_RAD_COMMENTS, :OLD.S5_RAD_ID, :OLD.S5_RAD_DATE, :OLD.S5_RAD_MODIFIED_BY
         , :OLD.S5_OPERATOR_CHK, :OLD.S5_OPERATOR_COMMENTS, :OLD.S5_OPERATOR_ID, :OLD.S5_OPERATOR_DATE
         , :OLD.S5_OPERATOR_MODIFIED_BY, :OLD.S5_RPFO_CHK, :OLD.S5_RPFO_COMMENTS, :OLD.S5_RPFO_ID
         , :OLD.S5_RPFO_DATE, :OLD.S5_RPFO_MODIFIED_BY
         , :OLD.S5_OTHER1_CHK, :OLD.S5_OTHER1_ID, :OLD.S5_OTHER1_COMMENTS, :OLD.S5_OTHER1_ACK_ID
         , :OLD.S5_OTHER1_ACK_DATE, :OLD.S5_OTHER1_ACK_MODIFIED_BY, :OLD.S5_OTHER2_CHK, :OLD.S5_OTHER2_ID
         , :OLD.S5_OTHER2_COMMENTS, :OLD.S5_OTHER2_ACK_ID, :OLD.S5_OTHER2_ACK_DATE, :OLD.S5_OTHER2_ACK_MODIFIED_BY
         , :OLD.S5_OTHER3_CHK, :OLD.S5_OTHER3_ID, :OLD.S5_OTHER3_COMMENTS, :OLD.S5_OTHER3_ACK_ID
         , :OLD.S5_OTHER3_ACK_DATE, :OLD.S5_OTHER3_ACK_MODIFIED_BY, :OLD.S6_SSO_ID, :OLD.S6_SSO_DATE
         , :OLD.S6_SSO_MODIFIED_BY, :OLD.S6_OPERATOR_ID, :OLD.S6_OPERATOR_DATE, :OLD.S6_OPERATOR_MODIFIED_BY
         , :OLD.FOLLOWUP_COMMENTS, :OLD.POST_CLOSURE_COMMENTS, :OLD.CREATED_BY, :OLD.CREATED_DATE
         , :OLD.MODIFIED_BY, :OLD.MODIFIED_DATE 
	 , :OLD.S4_ASSIGN_WRKR_ID, :OLD.S4_ASSIGN_WRKR_DATE, :OLD.S4_ASSIGN_WRKR_MODIFIED_BY, :OLD.DROP_FORM_CHK
	 , :OLD.S5_SSO_CHK, :OLD.S5_SSO_COMMENTS, :OLD.S5_SSO_ID, :OLD.S5_SSO_DATE, :OLD.S5_SSO_MODIFIED_BY
	 , :OLD.S6_OPERATOR_ACK, :OLD.S6_OPERATOR_ACK_DATE, :OLD.S6_OPERATOR_ACK_MODIFIED_BY
	);
         END IF; 
END;
/