--------------------------------------------------------
--  File created - Tuesday-March-21-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SSRL_RSW_USER_ROLES
--------------------------------------------------------

  CREATE TABLE "MCC_MAINT"."SSRL_RSW_USER_ROLES" 
   (	"USER_ROLE_ID" NUMBER, 
	"ROLE_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"STATUS_AI_CHK" VARCHAR2(1 BYTE) DEFAULT 'A', 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(30 BYTE), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MCC_MAINT_DATA" ;
REM INSERTING into MCC_MAINT.SSRL_RSW_USER_ROLES
SET DEFINE OFF;
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (94,2,569708,'A','POONAM',to_date('02/10/2023 19:54:19','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (21,2,563267,'I','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),'POONAM',to_date('02/10/2023 19:52:54','MM/DD/YYYY HH24:MI:SS'));
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (41,5,193054,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (42,5,129798,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (44,5,180190,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (45,5,122165,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (47,1,167657,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (48,3,395978,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (49,2,559657,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (50,2,43125,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (52,2,159360,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (53,2,81744,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (54,6,71277,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (55,6,243221,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (57,4,349550,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (58,4,263079,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (59,7,401250,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (81,1,122165,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (82,3,90859,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (83,6,92592,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (86,7,356697,'A','MCC_MAINT',to_date('07/28/2022 13:12:54','MM/DD/YYYY HH24:MI:SS'),null,null);
Insert into MCC_MAINT.SSRL_RSW_USER_ROLES (USER_ROLE_ID,ROLE_ID,USER_ID,STATUS_AI_CHK,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (93,6,558903,'A','POONAM',to_date('11/02/2022 11:34:14','MM/DD/YYYY HH24:MI:SS'),null,null);
--------------------------------------------------------
--  DDL for Index SSRL_RSW_USER_ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MCC_MAINT"."SSRL_RSW_USER_ROLES_PK" ON "MCC_MAINT"."SSRL_RSW_USER_ROLES" ("USER_ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MCC_MAINT_DATA" ;
--------------------------------------------------------
--  DDL for Index SSRL_RSW_USER_ROLES_UDX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "MCC_MAINT"."SSRL_RSW_USER_ROLES_UDX1" ON "MCC_MAINT"."SSRL_RSW_USER_ROLES" ("USER_ID", "ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MCC_MAINT_DATA" ;
--------------------------------------------------------
--  DDL for Trigger SSRL_RSW_USER_ROLES_BIUR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MCC_MAINT"."SSRL_RSW_USER_ROLES_BIUR" 
BEFORE INSERT OR UPDATE ON SSRL_RSW_USER_ROLES FOR EACH ROW
declare
    jn_operation varchar2(3);
begin

  if inserting and :new.USER_ROLE_ID is null
  then
    select SSRL_RSW_USER_ROLES_SEQ.nextval into :new.USER_ROLE_ID from dual;
  end if;

  if inserting and :new.created_by is null
  then
    :new.created_by := nvl(v('APP_USER'),user);
    :new.created_date := sysdate;
  end if;

  if updating
  then
    :new.modified_by := nvl(v('APP_USER'),user);
    :new.modified_date := sysdate;
  end if;
end;
/
ALTER TRIGGER "MCC_MAINT"."SSRL_RSW_USER_ROLES_BIUR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SSRL_RSW_USER_ROLES_AIUDR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MCC_MAINT"."SSRL_RSW_USER_ROLES_AIUDR" 
    AFTER INSERT OR UPDATE OR DELETE ON SSRL_RSW_USER_ROLES
    FOR EACH ROW
DECLARE
    JN_OPERATION VARCHAR2(3);
BEGIN
    IF INSERTING THEN
        JN_OPERATION := 'INS';
    ELSIF UPDATING THEN
        JN_OPERATION := 'UPD';
    ELSIF DELETING THEN
        JN_OPERATION := 'DEL';
    END IF;
    IF INSERTING OR UPDATING THEN
        INSERT INTO SSRL_RSW_USER_ROLES_JN
        ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , USER_ROLE_ID, ROLE_ID, USER_ID
         , STATUS_AI_CHK, CREATED_BY, CREATED_DATE, MODIFIED_BY
         , MODIFIED_DATE
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL, userenv('sessionid')
         , :NEW.USER_ROLE_ID, :NEW.ROLE_ID, :NEW.USER_ID
         , :NEW.STATUS_AI_CHK, :NEW.CREATED_BY, :NEW.CREATED_DATE, :NEW.MODIFIED_BY
         , :NEW.MODIFIED_DATE
         );
     END IF;
     IF DELETING THEN
         INSERT INTO SSRL_RSW_USER_ROLES_JN
         ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , USER_ROLE_ID, ROLE_ID, USER_ID
         , STATUS_AI_CHK, CREATED_BY, CREATED_DATE, MODIFIED_BY
         , MODIFIED_DATE
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL,userenv('sessionid')
         , :OLD.USER_ROLE_ID, :OLD.ROLE_ID, :OLD.USER_ID
         , :OLD.STATUS_AI_CHK, :OLD.CREATED_BY, :OLD.CREATED_DATE, :OLD.MODIFIED_BY
         , :OLD.MODIFIED_DATE );
         END IF;
END;
/
ALTER TRIGGER "MCC_MAINT"."SSRL_RSW_USER_ROLES_AIUDR" ENABLE;
--------------------------------------------------------
--  Constraints for Table SSRL_RSW_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "MCC_MAINT"."SSRL_RSW_USER_ROLES" MODIFY ("USER_ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "MCC_MAINT"."SSRL_RSW_USER_ROLES" ADD CONSTRAINT "SSRL_RSW_USER_ROLES_PK" PRIMARY KEY ("USER_ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MCC_MAINT_DATA"  ENABLE;
