create or replace TRIGGER CAPTAR.CABLE_INSTALL_UPLOAD_EXT_AIUDR
    AFTER INSERT OR UPDATE OR DELETE ON CABLE_INSTALL_UPLOAD_EXTRA
    FOR EACH ROW
DECLARE
    JN_OPERATION VARCHAR2(3);
BEGIN
    IF INSERTING THEN
        JN_OPERATION := 'INS';
    ELSIF UPDATING THEN
        JN_OPERATION := 'UPD';
    ELSIF DELETING THEN
        JN_OPERATION := 'DEL';
    END IF;
    IF INSERTING OR UPDATING THEN
        INSERT INTO CABLE_INSTALL_UPLOAD_EXTRA_JN 
        ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , CABLENUM, SECTOR_AREA, BEAMLINE_AREA
         , SECTOR_GROUP, PENETRATION, PENETRATION_II, PROJECT
         , INSTALLED_LENGTH, AREA_CODE, PHASE, CREATED_BY
         , CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, SECTOR_AREA_DEST
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL, userenv('sessionid')
         , :NEW.CABLENUM, :NEW.SECTOR_AREA, :NEW.BEAMLINE_AREA
         , :NEW.SECTOR_GROUP, :NEW.PENETRATION, :NEW.PENETRATION_II, :NEW.PROJECT
         , :NEW.INSTALLED_LENGTH, :NEW.AREA_CODE, :NEW.PHASE, :NEW.CREATED_BY
         , :NEW.CREATED_DATE, :NEW.MODIFIED_BY, :NEW.MODIFIED_DATE, :NEW.SECTOR_AREA_DEST
         );
     END IF;
     IF DELETING THEN
         INSERT INTO CABLE_INSTALL_UPLOAD_EXTRA_JN 
         ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , CABLENUM, SECTOR_AREA, BEAMLINE_AREA
         , SECTOR_GROUP, PENETRATION, PENETRATION_II, PROJECT
         , INSTALLED_LENGTH, AREA_CODE, PHASE, CREATED_BY
         , CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, SECTOR_AREA_DEST
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL,userenv('sessionid')
         , :OLD.CABLENUM, :OLD.SECTOR_AREA, :OLD.BEAMLINE_AREA
         , :OLD.SECTOR_GROUP, :OLD.PENETRATION, :OLD.PENETRATION_II, :OLD.PROJECT
         , :OLD.INSTALLED_LENGTH, :OLD.AREA_CODE, :OLD.PHASE, :OLD.CREATED_BY
         , :OLD.CREATED_DATE, :OLD.MODIFIED_BY, :OLD.MODIFIED_DATE, :OLD.SECTOR_AREA_DEST );
         END IF; 
END;
/