alter table ssrl_rsw_form add (
S5_SSO_CHK	VARCHAR2(1),
S5_SSO_COMMENTS	VARCHAR2(500),
S5_SSO_ID	NUMBER,
S5_SSO_DATE	DATE,
S5_SSO_MODIFIED_BY	VARCHAR2(30)
);

alter table ssrl_rsw_form_jn add (
S5_SSO_CHK	VARCHAR2(1),
S5_SSO_COMMENTS	VARCHAR2(500),
S5_SSO_ID	NUMBER,
S5_SSO_DATE	DATE,
S5_SSO_MODIFIED_BY	VARCHAR2(30)
);