CREATE OR REPLACE TRIGGER LCLS_INFRASTRUCTURE.MAGNET_STRING_AIUDR
  AFTER INSERT OR DELETE OR UPDATE ON LCLS_INFRASTRUCTURE.MAGNET_STRING
  REFERENCING FOR EACH ROW
  DECLARE
    JN_OPERATION VARCHAR2(3);
BEGIN
    IF INSERTING THEN
        JN_OPERATION := 'INS';
    ELSIF UPDATING THEN
        JN_OPERATION := 'UPD';
    ELSIF DELETING THEN
        JN_OPERATION := 'DEL';
    END IF;
    IF INSERTING OR UPDATING THEN
        INSERT INTO MAGNET_STRING_JN 
        ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , PSC_ID, BARCODE, ELEMENT
         , POLY_ID, PSC_TYPE, PSC_DEVICE, PSC_NODE
         , PSC_LOCN, ACSW_NODE, TS_NODE, MCOR_CRATE_NUM
         , MCOR_CRATE_CHAN, BULK_PS, IOC, CREATED_BY
         , DATE_CREATED, UPDATED_BY, DATE_UPDATED, ACSW_NAME
         , ACSW_HOST, ACSW_PLUG, HW_DISPLAY, UNIT_DISPLAY
         , LIMIT_DISPLAY, HW_AREA, COOLING_TYPE, STDZ_FUNC
	 , SAFETY_SYSTEM, SAFETY_BCS, SAFETY_PPS, SAFETY_MPS
	 , DEGAUSS_FUNC, CALIB_FUNC, DEGAUSS_SETL, DEGAUSS_RAMP_RATE
	 , DEGAUSS_WF_UOM, DEGAUSS_RAMP_RATE_UOM, DEGAUSS_SETL_UOM
	 , DEGAUSS_STEP_SIZE, DEGAUSS_STEP_SIZE_UOM
	 , DEGAUSS_WF_ELEM_CNT, DEGAUSS_WF, UNIT_DISPLAY_OVERRIDE, HW_DISPLAY_OVERRIDE
	 , SW_PS_STRING
	 ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL, userenv('sessionid')
         , :NEW.PSC_ID, :NEW.BARCODE, :NEW.ELEMENT
         , :NEW.POLY_ID, :NEW.PSC_TYPE, :NEW.PSC_DEVICE, :NEW.PSC_NODE
         , :NEW.PSC_LOCN, :NEW.ACSW_NODE, :NEW.TS_NODE, :NEW.MCOR_CRATE_NUM
         , :NEW.MCOR_CRATE_CHAN, :NEW.BULK_PS, :NEW.IOC, :NEW.CREATED_BY
         , :NEW.DATE_CREATED, :NEW.UPDATED_BY, :NEW.DATE_UPDATED, :NEW.ACSW_NAME
         , :NEW.ACSW_HOST, :NEW.ACSW_PLUG, :NEW.HW_DISPLAY, :NEW.UNIT_DISPLAY
         , :NEW.LIMIT_DISPLAY, :NEW.HW_AREA, :NEW.COOLING_TYPE, :NEW.STDZ_FUNC
	 , :NEW.SAFETY_SYSTEM, :NEW.SAFETY_BCS, :NEW.SAFETY_PPS, :NEW.SAFETY_MPS
	 , :NEW.DEGAUSS_FUNC, :NEW.CALIB_FUNC, :NEW.DEGAUSS_SETL, :NEW.DEGAUSS_RAMP_RATE
	 , :NEW.DEGAUSS_WF_UOM, :NEW.DEGAUSS_RAMP_RATE_UOM, :NEW.DEGAUSS_SETL_UOM
	 , :NEW.DEGAUSS_STEP_SIZE, :NEW.DEGAUSS_STEP_SIZE_UOM
	 , :NEW.DEGAUSS_WF_ELEM_CNT, :NEW.DEGAUSS_WF, :NEW.UNIT_DISPLAY_OVERRIDE, :NEW.HW_DISPLAY_OVERRIDE
	 , :NEW.SW_PS_STRING
        );
     END IF;
     IF DELETING THEN
         INSERT INTO MAGNET_STRING_JN 
         ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , PSC_ID, BARCODE, ELEMENT
         , POLY_ID, PSC_TYPE, PSC_DEVICE, PSC_NODE
         , PSC_LOCN, ACSW_NODE, TS_NODE, MCOR_CRATE_NUM
         , MCOR_CRATE_CHAN, BULK_PS, IOC, CREATED_BY
         , DATE_CREATED, UPDATED_BY, DATE_UPDATED, ACSW_NAME
         , ACSW_HOST, ACSW_PLUG, HW_DISPLAY, UNIT_DISPLAY
         , LIMIT_DISPLAY, HW_AREA, COOLING_TYPE, STDZ_FUNC
	 , SAFETY_SYSTEM, SAFETY_BCS, SAFETY_PPS, SAFETY_MPS
	 , DEGAUSS_FUNC, CALIB_FUNC, DEGAUSS_SETL, DEGAUSS_RAMP_RATE
	 , DEGAUSS_WF_UOM, DEGAUSS_RAMP_RATE_UOM, DEGAUSS_SETL_UOM
	 , DEGAUSS_STEP_SIZE, DEGAUSS_STEP_SIZE_UOM
	 , DEGAUSS_WF_ELEM_CNT, DEGAUSS_WF, UNIT_DISPLAY_OVERRIDE, HW_DISPLAY_OVERRIDE
	 , SW_PS_STRING
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL,userenv('sessionid')
         , :OLD.PSC_ID, :OLD.BARCODE, :OLD.ELEMENT
         , :OLD.POLY_ID, :OLD.PSC_TYPE, :OLD.PSC_DEVICE, :OLD.PSC_NODE
         , :OLD.PSC_LOCN, :OLD.ACSW_NODE, :OLD.TS_NODE, :OLD.MCOR_CRATE_NUM
         , :OLD.MCOR_CRATE_CHAN, :OLD.BULK_PS, :OLD.IOC, :OLD.CREATED_BY
         , :OLD.DATE_CREATED, :OLD.UPDATED_BY, :OLD.DATE_UPDATED, :OLD.ACSW_NAME
         , :OLD.ACSW_HOST, :OLD.ACSW_PLUG, :OLD.HW_DISPLAY, :OLD.UNIT_DISPLAY
         , :OLD.LIMIT_DISPLAY, :OLD.HW_AREA, :OLD.COOLING_TYPE, :OLD.STDZ_FUNC
	 , :OLD.SAFETY_SYSTEM, :OLD.SAFETY_BCS, :OLD.SAFETY_PPS, :OLD.SAFETY_MPS
	 , :OLD.DEGAUSS_FUNC, :OLD.CALIB_FUNC, :OLD.DEGAUSS_SETL, :OLD.DEGAUSS_RAMP_RATE
	 , :OLD.DEGAUSS_WF_UOM, :OLD.DEGAUSS_RAMP_RATE_UOM, :OLD.DEGAUSS_SETL_UOM
	 , :OLD.DEGAUSS_STEP_SIZE, :OLD.DEGAUSS_STEP_SIZE_UOM
	 , :OLD.DEGAUSS_WF_ELEM_CNT, :OLD.DEGAUSS_WF, :OLD.UNIT_DISPLAY_OVERRIDE, :OLD.HW_DISPLAY_OVERRIDE
	 , :OLD.SW_PS_STRING
	 );
         END IF; 
END;
/