
  CREATE TABLE "MCC_MAINT"."EMP_NOMINATION_DUE_JN" 
   (	"JN_OPERATION" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"JN_ORACLE_USER" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"JN_DATETIME" DATE NOT NULL ENABLE, 
	"JN_NOTES" VARCHAR2(240 BYTE), 
	"JN_APPLN" VARCHAR2(30 BYTE), 
	"JN_SESSION" NUMBER(38,0), 
	"DUE_DATE" DATE, 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MCC_MAINT_DATA" ;

