CREATE OR REPLACE EDITIONABLE TRIGGER "MCC_MAINT"."EMP_NOMINATION_DUE_AIUDR" 
    AFTER INSERT OR UPDATE OR DELETE ON EMP_NOMINATION_DUE
    FOR EACH ROW
DECLARE
    JN_OPERATION VARCHAR2(3);
BEGIN
    IF INSERTING THEN
        JN_OPERATION := 'INS';
    ELSIF UPDATING THEN
        JN_OPERATION := 'UPD';
    ELSIF DELETING THEN
        JN_OPERATION := 'DEL';
    END IF;
    IF INSERTING OR UPDATING THEN
        INSERT INTO EMP_NOMINATION_DUE_JN 
        ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , DUE_DATE, ID
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL, userenv('sessionid')
         , :NEW.DUE_DATE, :NEW.ID
         );
     END IF;
     IF DELETING THEN
         INSERT INTO EMP_NOMINATION_DUE_JN 
         ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , DUE_DATE, ID
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL,userenv('sessionid')
         , :OLD.DUE_DATE, :OLD.ID );
         END IF; 
END;
/