drop table SSRL_RSW_AREA;
create table SSRL_RSW_AREA (
	AREA_ID		NUMBER NOT NULL,
	AREA		VARCHAR2(50) NOT NULL,
	STATUS_AI_CHK	VARCHAR2(1),
	DISPLAY_ORDER	NUMBER,
	DESCRIPTION	VARCHAR2(4000),
	CREATED_BY	VARCHAR2(30) NOT NULL,
	CREATED_DATE	DATE NOT NULL,
	MODIFIED_BY	VARCHAR2(30),
	MODIFIED_DATE	DATE
);


ALTER TABLE SSRL_RSW_AREA
ADD CONSTRAINT SSRL_RSW_AREA_PK PRIMARY KEY (AREA_ID)
using index;

drop sequence SSRL_RSW_AREA_SEQ;
CREATE SEQUENCE SSRL_RSW_AREA_SEQ
MINVALUE 1 
MAXVALUE 999999999999999999999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE  
NOORDER  
NOCYCLE;

drop table SSRL_RSW_AREA_JN;
create table SSRL_RSW_AREA_JN (
	JN_OPERATION VARCHAR2(3) NOT NULL ,
	JN_ORACLE_USER VARCHAR2(30) NOT NULL ,
	JN_DATETIME DATE NOT NULL ,
	JN_NOTES VARCHAR2(240) ,
	JN_APPLN VARCHAR2(30) ,
	JN_SESSION NUMBER(38) ,
	AREA_ID		NUMBER NOT NULL,
	AREA		VARCHAR2(50) NOT NULL,
	STATUS_AI_CHK	VARCHAR2(1),
	DISPLAY_ORDER	NUMBER,
	DESCRIPTION	VARCHAR2(4000),
	CREATED_BY	VARCHAR2(30) ,
	CREATED_DATE	DATE ,
	MODIFIED_BY	VARCHAR2(30),
	MODIFIED_DATE	DATE
);

