-- Create Database Trigger --
SET DEFINE OFF;
CREATE OR REPLACE TRIGGER MCC_MAINT.SSRL_RSW_AREA_AIUDR
    AFTER INSERT OR UPDATE OR DELETE ON SSRL_RSW_AREA
    FOR EACH ROW
DECLARE
    JN_OPERATION VARCHAR2(3);
BEGIN
    IF INSERTING THEN
        JN_OPERATION := 'INS';
    ELSIF UPDATING THEN
        JN_OPERATION := 'UPD';
    ELSIF DELETING THEN
        JN_OPERATION := 'DEL';
    END IF;
    IF INSERTING OR UPDATING THEN
        INSERT INTO SSRL_RSW_AREA_JN 
        ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , AREA_ID, AREA, STATUS_AI_CHK
         , DISPLAY_ORDER, DESCRIPTION, CREATED_BY, CREATED_DATE
         , MODIFIED_BY, MODIFIED_DATE
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL, userenv('sessionid')
         , :NEW.AREA_ID, :NEW.AREA, :NEW.STATUS_AI_CHK
         , :NEW.DISPLAY_ORDER, :NEW.DESCRIPTION, :NEW.CREATED_BY, :NEW.CREATED_DATE
         , :NEW.MODIFIED_BY, :NEW.MODIFIED_DATE
         );
     END IF;
     IF DELETING THEN
         INSERT INTO SSRL_RSW_AREA_JN 
         ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , AREA_ID, AREA, STATUS_AI_CHK
         , DISPLAY_ORDER, DESCRIPTION, CREATED_BY, CREATED_DATE
         , MODIFIED_BY, MODIFIED_DATE
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL,userenv('sessionid')
         , :OLD.AREA_ID, :OLD.AREA, :OLD.STATUS_AI_CHK
         , :OLD.DISPLAY_ORDER, :OLD.DESCRIPTION, :OLD.CREATED_BY, :OLD.CREATED_DATE
         , :OLD.MODIFIED_BY, :OLD.MODIFIED_DATE );
         END IF; 
END;
/