-- Create Database Trigger --
SET DEFINE OFF;
CREATE OR REPLACE TRIGGER MCC_MAINT.SSRL_RSW_BEAMLINE_MGR_AIUDR
    AFTER INSERT OR UPDATE OR DELETE ON SSRL_RSW_BEAMLINE_MGR
    FOR EACH ROW
DECLARE
    JN_OPERATION VARCHAR2(3);
BEGIN
    IF INSERTING THEN
        JN_OPERATION := 'INS';
    ELSIF UPDATING THEN
        JN_OPERATION := 'UPD';
    ELSIF DELETING THEN
        JN_OPERATION := 'DEL';
    END IF;
    IF INSERTING OR UPDATING THEN
        INSERT INTO SSRL_RSW_BEAMLINE_MGR_JN 
        ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , AREA_ID, BEAMLINE_MGR_ID, STATUS_AI_CHK
         , CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL, userenv('sessionid')
         , :NEW.AREA_ID, :NEW.BEAMLINE_MGR_ID, :NEW.STATUS_AI_CHK
         , :NEW.CREATED_BY, :NEW.CREATED_DATE, :NEW.MODIFIED_BY, :NEW.MODIFIED_DATE
         );
     END IF;
     IF DELETING THEN
         INSERT INTO SSRL_RSW_BEAMLINE_MGR_JN 
         ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , AREA_ID, BEAMLINE_MGR_ID, STATUS_AI_CHK
         , CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL,userenv('sessionid')
         , :OLD.AREA_ID, :OLD.BEAMLINE_MGR_ID, :OLD.STATUS_AI_CHK
         , :OLD.CREATED_BY, :OLD.CREATED_DATE, :OLD.MODIFIED_BY, :OLD.MODIFIED_DATE );
         END IF; 
END;
/