drop table ssrl_rsw_attachment;
create table ssrl_rsw_attachment (
FILE_ID		NUMBER not null,
FORM_ID		NUMBER not null,
ID		NUMBER,
DOC_SIZE	NUMBER,
NAME		VARCHAR2(500),
COMMENTS	VARCHAR2(500),
MIME_TYPE	VARCHAR2(4000),
BLOB_CONTENT	BLOB,
CREATED_BY	VARCHAR2(30) not null,
CREATED_DATE	DATE not null,
MODIFIED_BY	VARCHAR2(30),
MODIFIED_DATE	DATE
);

alter table ssrl_rsw_attachment
add CONSTRAINT ssrl_rsw_attachment_PK PRIMARY KEY (FILE_ID)
  USING INDEX ;

drop table ssrl_rsw_attachment_jn;
create table ssrl_rsw_attachment_JN (
JN_OPERATION	VARCHAR2(3) not null,
JN_ORACLE_USER	VARCHAR2(30) not null,
JN_DATETIME	DATE not null,
JN_NOTES	VARCHAR2(240),
JN_APPLN	VARCHAR2(30),
JN_SESSION	NUMBER,
FILE_ID		NUMBER not null,
FORM_ID		NUMBER not null,
ID		NUMBER,
DOC_SIZE	NUMBER,
NAME		VARCHAR2(500),
COMMENTS	VARCHAR2(500),
MIME_TYPE	VARCHAR2(4000),
BLOB_CONTENT	BLOB,
CREATED_BY	VARCHAR2(30) ,
CREATED_DATE	DATE ,
MODIFIED_BY	VARCHAR2(30),
MODIFIED_DATE	DATE
);

drop sequence ssrl_rsw_attachment_SEQ;
  CREATE SEQUENCE ssrl_rsw_attachment_SEQ
  MINVALUE 1 
  MAXVALUE 9999999999999999999999999999 
  INCREMENT BY 1 
  START WITH 1 
  CACHE 20 
  NOORDER  
  NOCYCLE ;

