drop table SSRL_RSW_BEAMLINE_MGR ;
create table SSRL_RSW_BEAMLINE_MGR (
	AREA_ID		NUMBER  NOT NULL,
	BEAMLINE_MGR_ID	NUMBER(7)  NOT NULL,
	STATUS_AI_CHK	VARCHAR2(1),
	CREATED_BY	VARCHAR2(30) NOT NULL,
	CREATED_DATE	DATE NOT NULL,
	MODIFIED_BY	VARCHAR2(30),
	MODIFIED_DATE	DATE
);

ALTER TABLE SSRL_RSW_BEAMLINE_MGR
ADD CONSTRAINT SSRL_RSW_BEAMLINE_MGR_PK PRIMARY KEY (AREA_ID, BEAMLINE_MGR_ID)
using index;

ALTER TABLE SSRL_RSW_BEAMLINE_MGR
ADD CONSTRAINT SSRL_RSW_BEAMLINE_MGR_FK1 FOREIGN KEY (AREA_ID)
references SSRL_RSW_AREA (AREA_ID);

drop table SSRL_RSW_BEAMLINE_MGR_JN ;
create table SSRL_RSW_BEAMLINE_MGR_JN (
	JN_OPERATION	VARCHAR2(3) NOT NULL ,
	JN_ORACLE_USER	VARCHAR2(30) NOT NULL ,
	JN_DATETIME	DATE NOT NULL ,
	JN_NOTES	VARCHAR2(240) ,
	JN_APPLN	VARCHAR2(30) ,
	JN_SESSION	NUMBER(38) ,
	AREA_ID		NUMBER  NOT NULL,
	BEAMLINE_MGR_ID	NUMBER(7)  NOT NULL,
	STATUS_AI_CHK	VARCHAR2(1),
	CREATED_BY	VARCHAR2(30),
	CREATED_DATE	DATE,
	MODIFIED_BY	VARCHAR2(30),
	MODIFIED_DATE	DATE
);


