  drop TABLE MCC_MAINT.SSRL_RSW_FORM_STATUS ;

  CREATE TABLE MCC_MAINT.SSRL_RSW_FORM_STATUS 
   (	FORM_STATUS_ID NUMBER(2) NOT NULL, 
	STATUS VARCHAR2(100), 
	DESCRIPTION VARCHAR2(1000), 
	CONSTRAINT SSRL_RSW_FORM_STATUS_PK PRIMARY KEY (FORM_STATUS_ID)
    );

SET DEFINE OFF;
Insert into MCC_MAINT.SSRL_RSW_FORM_STATUS (FORM_STATUS_ID,STATUS,DESCRIPTION) values (1,'New',null);
Insert into MCC_MAINT.SSRL_RSW_FORM_STATUS (FORM_STATUS_ID,STATUS,DESCRIPTION) values (2,'Work Approved (not yet Released)',null);
Insert into MCC_MAINT.SSRL_RSW_FORM_STATUS (FORM_STATUS_ID,STATUS,DESCRIPTION) values (3,'Work Released',null);
Insert into MCC_MAINT.SSRL_RSW_FORM_STATUS (FORM_STATUS_ID,STATUS,DESCRIPTION) values (4,'Work Complete',null);
Insert into MCC_MAINT.SSRL_RSW_FORM_STATUS (FORM_STATUS_ID,STATUS,DESCRIPTION) values (5,'Transferred',null);
Insert into MCC_MAINT.SSRL_RSW_FORM_STATUS (FORM_STATUS_ID,STATUS,DESCRIPTION) values (6,'Closed',null);
Insert into MCC_MAINT.SSRL_RSW_FORM_STATUS (FORM_STATUS_ID,STATUS,DESCRIPTION) values (7,'Dropped',null);
commit;