-- BACKUP SCORE TABLES_MCCO.SQL
-- IN SQLPLUS LOG ONTO THE TARGET INSTANCE/SCHEMA (SCORE@MCCO) AND INVOKE THIS SCRIPT.
-- THE SCRIPT CREATES A LOG FILE IN THE SQLPLUS LOGON DIRECTORY.

SET SERVEROUTPUT ON SIZE UNLIMITED
SET TIMING ON
SPOOL BACKUP_SCORE_TABLES_MCCO.LOG

PROMPT = BEGIN =

DECLARE
  V_TABLE_LIST     VARCHAR2(32767);
  V_ERRMSG         VARCHAR2(1000);
  V_DELIMITER      VARCHAR2(1) := ',';
  
  BACKUP_PROCESS_ERROR    EXCEPTION;
  
BEGIN

  V_TABLE_LIST := 'SCORE_SNAPSHOT_GRP,SCORE_SNAPSHOT_GRP_JN,SCORE_SNAPSHOT_GRP_SGNL,SCORE_SNAPSHOT_GRP_SGNL_JN,SCORE_SNAPSHOT_SGNL,SCORE_SNAPSHOT_SGNL_JN,SCORE_SUBSYSTEMS,SCORE_SUBSYSTEMS_JN,SCORE_UPLOAD,SCORE_UPLOAD_JN,SCORE_UPLOAD_LOG,SCORE_DEVICETYPES,SCORE_DEVICETYPES_JN,SYST,CHECK_FILE_LOG,CHECK_FILE_ROW,APEX_ACCESS_CONTROL,APEX_ACCESS_SETUP';
  V_ERRMSG     := NULL;
  
  --------
  
  GLOBAL_PKG.MAKE_TABLE_BACKUP(V_TABLE_LIST,V_ERRMSG,V_DELIMITER);

  IF ( V_ERRMSG IS NULL ) THEN
    DBMS_OUTPUT.PUT_LINE('PROCESS: BACKUP TABLES FOR SCORE CREATED.');
  ELSE
    RAISE BACKUP_PROCESS_ERROR;
  END IF;
  
  EXCEPTION
    WHEN BACKUP_PROCESS_ERROR THEN
      DBMS_OUTPUT.PUT_LINE('ERROR: '||V_ERRMSG);
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);

END;
/

PROMPT = DONE =

SPOOL OFF
