create or replace TRIGGER "LCLS_INFRASTRUCTURE"."MAGNET_STRING_AIUDR" 
    AFTER INSERT OR UPDATE OR DELETE ON MAGNET_STRING
    FOR EACH ROW
DECLARE
    JN_OPERATION VARCHAR2(3);
BEGIN
    IF INSERTING THEN
        JN_OPERATION := 'INS';
    ELSIF UPDATING THEN
        JN_OPERATION := 'UPD';
    ELSIF DELETING THEN
        JN_OPERATION := 'DEL';
    END IF;
    IF INSERTING OR UPDATING THEN
        INSERT INTO MAGNET_STRING_JN 
        ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , PSC_ID, BARCODE, ELEMENT
         , POLY_ID, PSC_TYPE, PSC_DEVICE, PSC_NODE
         , PSC_LOCN, ACSW_NODE, TS_NODE, MCOR_CRATE_NUM
         , MCOR_CRATE_CHAN, BULK_PS, IOC, CREATED_BY
         , DATE_CREATED, UPDATED_BY, DATE_UPDATED, ACSW_NAME
         , ACSW_HOST, ACSW_PLUG, HW_DISPLAY, UNIT_DISPLAY
         , LIMIT_DISPLAY, HW_AREA, COOLING_TYPE
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL, userenv('sessionid')
         , :NEW.PSC_ID, :NEW.BARCODE, :NEW.ELEMENT
         , :NEW.POLY_ID, :NEW.PSC_TYPE, :NEW.PSC_DEVICE, :NEW.PSC_NODE
         , :NEW.PSC_LOCN, :NEW.ACSW_NODE, :NEW.TS_NODE, :NEW.MCOR_CRATE_NUM
         , :NEW.MCOR_CRATE_CHAN, :NEW.BULK_PS, :NEW.IOC, :NEW.CREATED_BY
         , :NEW.DATE_CREATED, :NEW.UPDATED_BY, :NEW.DATE_UPDATED, :NEW.ACSW_NAME
         , :NEW.ACSW_HOST, :NEW.ACSW_PLUG, :NEW.HW_DISPLAY, :NEW.UNIT_DISPLAY
         , :NEW.LIMIT_DISPLAY, :NEW.HW_AREA, :NEW.COOLING_TYPE
         );
     END IF;
     IF DELETING THEN
         INSERT INTO MAGNET_STRING_JN 
         ( JN_OPERATION, JN_ORACLE_USER, JN_DATETIME, JN_NOTES, JN_APPLN, JN_SESSION
         , PSC_ID, BARCODE, ELEMENT
         , POLY_ID, PSC_TYPE, PSC_DEVICE, PSC_NODE
         , PSC_LOCN, ACSW_NODE, TS_NODE, MCOR_CRATE_NUM
         , MCOR_CRATE_CHAN, BULK_PS, IOC, CREATED_BY
         , DATE_CREATED, UPDATED_BY, DATE_UPDATED, ACSW_NAME
         , ACSW_HOST, ACSW_PLUG, HW_DISPLAY, UNIT_DISPLAY
         , LIMIT_DISPLAY, HW_AREA, COOLING_TYPE
         ) VALUES (jn_operation, NVL(V('APP_USER'),USER), SYSDATE, NULL, NULL,userenv('sessionid')
         , :OLD.PSC_ID, :OLD.BARCODE, :OLD.ELEMENT
         , :OLD.POLY_ID, :OLD.PSC_TYPE, :OLD.PSC_DEVICE, :OLD.PSC_NODE
         , :OLD.PSC_LOCN, :OLD.ACSW_NODE, :OLD.TS_NODE, :OLD.MCOR_CRATE_NUM
         , :OLD.MCOR_CRATE_CHAN, :OLD.BULK_PS, :OLD.IOC, :OLD.CREATED_BY
         , :OLD.DATE_CREATED, :OLD.UPDATED_BY, :OLD.DATE_UPDATED, :OLD.ACSW_NAME
         , :OLD.ACSW_HOST, :OLD.ACSW_PLUG, :OLD.HW_DISPLAY, :OLD.UNIT_DISPLAY
         , :OLD.LIMIT_DISPLAY, :OLD.HW_AREA, :OLD.COOLING_TYPE );
         END IF; 
END;
/